"""Coast FIRE Scenario Planner.

Projects a household's path to a target portfolio plus a paid-off home, sweeping
every invest-vs-prepay split. Contributions flow through real registered
accounts (RRSP / TFSA / non-registered) with contribution room enforced, and the
RRSP deduction generates an Alberta + federal tax refund that is recycled back
into the plan. Every input below is configurable from the sidebar.
"""

import streamlit as st
import pandas as pd
import plotly.graph_objects as go
from dataclasses import dataclass, field
from datetime import date
import colorsys

st.set_page_config(page_title="Coast FIRE Planner", page_icon="🎯", layout="wide", initial_sidebar_state="expanded")

st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;600;700;800&display=swap');
html, body, [class*="css"] { font-family: 'Syne', sans-serif; }
.stApp { background: linear-gradient(135deg, #0a0e1a 0%, #0d1422 50%, #0a0e1a 100%); }
h1, h2, h3 { font-family: 'Syne', sans-serif; font-weight: 800; }
div[data-testid="metric-container"] { background: #131929; border-radius: 10px; padding: 12px 16px; border: 1px solid #2a3550; }
.stButton > button { background: linear-gradient(135deg, #1c6ef3 0%, #1557d4 100%); color: white; border: none; border-radius: 8px; font-family: 'Space Mono', monospace; font-weight: 700; letter-spacing: 0.05em; padding: 8px 16px; transition: all 0.2s; width: 100%; }
.stButton > button:hover { background: linear-gradient(135deg, #2980ff 0%, #1c6ef3 100%); transform: translateY(-1px); box-shadow: 0 4px 20px rgba(28,110,243,0.4); }
.info-box { background: #0f1e33; border: 1px solid #1c3a5e; border-radius: 8px; padding: 12px 14px; font-family: 'Space Mono', monospace; font-size: 0.8em; color: #7c90b0; margin: 6px 0; }
.section-title { font-family: 'Space Mono', monospace; font-size: 0.7em; letter-spacing: 0.15em; color: #4dabf7; text-transform: uppercase; margin: 18px 0 6px 0; border-bottom: 1px solid #2a3550; padding-bottom: 5px; }
.stDataFrame { border: 1px solid #2a3550; border-radius: 10px; }
</style>
""", unsafe_allow_html=True)

MONTHS_ABBR = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]

# ─── Tax engine ───────────────────────────────────────────────────────────────
# Brackets are (upper limit, rate) pairs, lowest first. The top entry's limit is
# ignored — the highest bracket always runs to infinity. Defaults are the 2025
# federal and Alberta schedules; both tables are editable in the app, so they can
# be rolled forward without touching this file.
FED_BRACKETS_DEFAULT = [(57_375.0, 0.145), (114_750.0, 0.205), (177_882.0, 0.26),
                        (253_414.0, 0.29), (float("inf"), 0.33)]
AB_BRACKETS_DEFAULT  = [(60_000.0, 0.08), (151_234.0, 0.10), (181_481.0, 0.12),
                        (241_974.0, 0.13), (362_961.0, 0.14), (float("inf"), 0.15)]
FED_BPA_DEFAULT = 16_129.0
AB_BPA_DEFAULT  = 22_323.0


def bracket_tax(income, brackets):
    """Tax before credits on `income` under a progressive bracket table."""
    tax, lower = 0.0, 0.0
    for limit, rate in brackets:
        if income <= lower:
            break
        tax += (min(income, limit) - lower) * rate
        lower = limit
    return tax


def schedule_tax(income, brackets, bpa):
    """Tax for one jurisdiction, net of the basic personal amount credit.

    The BPA is a non-refundable credit valued at the lowest bracket rate, which is
    why it is netted off here rather than subtracted from income.
    """
    income = max(0.0, income)
    credit = min(income, max(0.0, bpa)) * brackets[0][1]
    return max(0.0, bracket_tax(income, brackets) - credit)


def total_tax(income, cfg):
    return (schedule_tax(income, cfg.fed_brackets, cfg.fed_bpa)
            + schedule_tax(income, cfg.ab_brackets, cfg.ab_bpa))


def marginal_rate(income, cfg):
    def rate_at(brackets):
        lower = 0.0
        for limit, rate in brackets:
            if income <= limit:
                return rate
            lower = limit
        return brackets[-1][1]
    return rate_at(cfg.fed_brackets) + rate_at(cfg.ab_brackets)


def refund_for(gross, deduction, cfg):
    """Refund generated by an RRSP deduction: the tax delta it actually removes.

    Computed as a difference of two full tax calculations rather than
    `deduction x marginal rate`, so a deduction that spans a bracket boundary is
    valued correctly. Non-refundable credits are identical on both sides and
    cancel out, which is why CPP/EI credits can be left out without affecting the
    result.
    """
    if deduction <= 0 or gross <= 0:
        return 0.0
    d = min(deduction, gross)
    return max(0.0, total_tax(gross, cfg) - total_tax(gross - d, cfg))


# ─── Configuration ────────────────────────────────────────────────────────────
BUCKETS = ["RRSP – You", "RRSP – Spouse", "TFSA – You", "TFSA – Spouse", "Non-registered"]
NONREG = "Non-registered"


@dataclass
class Person:
    label: str
    income: float
    rrsp_bal: float
    tfsa_bal: float
    rrsp_room: float
    tfsa_room: float
    ytd_rrsp: float = 0.0     # RRSP already contributed earlier in the start year
    employee_pct: float = 0.0  # group-plan contribution, % of salary
    employer_pct: float = 0.0  # employer match, % of salary


@dataclass
class Cfg:
    you: Person
    spouse: Person
    # cash flow
    savings: float
    savings_growth: float
    salary_growth: float
    bonus: float
    bonus_month: int
    # balances & returns
    nonreg_bal: float
    inv_return: float
    nonreg_drag: float
    # contribution room accrual
    tfsa_annual: float
    rrsp_accrual_pct: float
    rrsp_annual_max: float
    limit_indexation: float
    # group plan
    group_is_rrsp: bool         # True: group RRSP. False: DC pension (PA model).
    payroll_from_savings: bool
    # mortgage
    mort_bal: float
    mort_rate: float
    mort_weekly: float
    mort_orig: float
    prepay_pct: float
    prepay_enforce: bool
    redirect_freed: bool
    # allocation
    waterfall: list
    spill_to_invest: bool
    # refund
    refund_month: int
    refund_rule: str
    # tax tables
    fed_brackets: list
    ab_brackets: list
    fed_bpa: float
    ab_bpa: float
    # goal
    goal: float
    goal_basis: str             # "gross" | "net"
    rrsp_withdraw_rate: float
    require_mort_paid: bool
    # horizon
    max_months: int
    start: date


def month_date(cfg, idx):
    y = cfg.start.year + (cfg.start.month - 1 + idx) // 12
    m = (cfg.start.month - 1 + idx) % 12 + 1
    return date(y, m, 1)


def month_label(cfg, idx):
    d = month_date(cfg, idx)
    return f"{MONTHS_ABBR[d.month - 1]} {d.year}"


def next_month_start(today=None):
    """First of the month after `today` — the projection always starts next month."""
    d = today or date.today()
    return date(d.year + 1, 1, 1) if d.month == 12 else date(d.year, d.month + 1, 1)


# ─── Simulation ───────────────────────────────────────────────────────────────
def run_scenario(cfg, invest_pct):
    """Project one invest-vs-prepay split month by month.

    `invest_pct` of each month's free cash goes into the investment waterfall and
    the rest at the mortgage. The run stops the month the goal is met, so every
    summary it returns is "as at stop" — see `months_run` for the horizon behind
    the numbers.
    """
    p = invest_pct / 100.0

    bal = {"RRSP – You": cfg.you.rrsp_bal, "TFSA – You": cfg.you.tfsa_bal,
           "RRSP – Spouse": cfg.spouse.rrsp_bal, "TFSA – Spouse": cfg.spouse.tfsa_bal,
           NONREG: cfg.nonreg_bal}
    room = {"RRSP – You": cfg.you.rrsp_room, "TFSA – You": cfg.you.tfsa_room,
            "RRSP – Spouse": cfg.spouse.rrsp_room, "TFSA – Spouse": cfg.spouse.tfsa_room}
    contrib_total = {k: 0.0 for k in BUCKETS}

    inc = {"you": cfg.you.income, "sp": cfg.spouse.income}
    # Contributions already made earlier in the start calendar year still generate
    # a refund, so they seed this year's deduction pool. They are assumed to be
    # already reflected in the remaining room entered above, so room is untouched.
    deduct = {"you": cfg.you.ytd_rrsp, "sp": cfg.spouse.ytd_rrsp}
    grp_pct = cfg.spouse.employee_pct + cfg.spouse.employer_pct
    # Under a group RRSP the employer's share of those YTD contributions was also
    # taxable income, so it has to be added back before the refund is valued.
    extra_inc_sp = (cfg.spouse.ytd_rrsp * cfg.spouse.employer_pct / grp_pct
                    if cfg.group_is_rrsp and grp_pct > 0 else 0.0)

    savings      = cfg.savings
    tfsa_annual  = cfg.tfsa_annual
    rrsp_max     = cfg.rrsp_annual_max
    mort         = cfg.mort_bal
    mort_rate_m  = cfg.mort_rate / 12
    mort_monthly = cfg.mort_weekly * 52 / 12
    inv_rate_m   = cfg.inv_return / 100 / 12
    nonreg_rate_m = cfg.inv_return / 100 * (1 - cfg.nonreg_drag / 100) / 12

    prepay_used = refund_due = pa_accum = 0.0
    total_refund = total_idle = total_payroll = 0.0
    mort_paid_label = goal_label = None
    goal_idx = None
    rows = []

    for i in range(cfg.max_months):
        d, lbl = month_date(cfg, i), month_label(cfg, i)

        # ── New calendar year: file last year's return, then accrue new room ──
        if d.month == 1 and i > 0:
            refund_due = (refund_for(inc["you"], deduct["you"], cfg)
                          + refund_for(inc["sp"] + extra_inc_sp, deduct["sp"], cfg))
            # RRSP room accrues on the year just ended, net of any pension
            # adjustment; TFSA room accrues at the flat annual amount.
            room["RRSP – You"] += min(inc["you"] * cfg.rrsp_accrual_pct / 100, rrsp_max)
            room["RRSP – Spouse"] += max(0.0, min(inc["sp"] * cfg.rrsp_accrual_pct / 100,
                                                  rrsp_max) - pa_accum)
            room["TFSA – You"] += tfsa_annual
            room["TFSA – Spouse"] += tfsa_annual
            pa_accum = prepay_used = extra_inc_sp = 0.0
            deduct = {"you": 0.0, "sp": 0.0}
            inc["you"] *= 1 + cfg.salary_growth / 100
            inc["sp"]  *= 1 + cfg.salary_growth / 100
            savings    *= 1 + cfg.savings_growth / 100
            tfsa_annual *= 1 + cfg.limit_indexation / 100
            rrsp_max    *= 1 + cfg.limit_indexation / 100

        # ── Spouse's group plan, deducted at source before any other saving ──
        ee = inc["sp"] * cfg.spouse.employee_pct / 100 / 12
        er = inc["sp"] * cfg.spouse.employer_pct / 100 / 12
        if cfg.group_is_rrsp:
            # A group RRSP consumes the member's own RRSP room, so both halves are
            # scaled back together once that room runs out.
            if ee + er > room["RRSP – Spouse"]:
                scale = room["RRSP – Spouse"] / (ee + er) if ee + er > 0 else 0.0
                ee, er = ee * max(0.0, scale), er * max(0.0, scale)
            room["RRSP – Spouse"] -= ee + er
            deduct["sp"] += ee + er
            extra_inc_sp += er          # employer match is a taxable benefit
        else:
            # DC pension: employer money is not income, only the employee half is
            # deductible, and the pension adjustment eats next year's RRSP room.
            deduct["sp"] += ee
            pa_accum += ee + er
        # Deposited after the growth step below, alongside every other
        # contribution, so a month's return is not credited on it twice.
        payroll_in = ee + er
        contrib_total["RRSP – Spouse"] += payroll_in
        total_payroll += payroll_in

        # ── Cash available this month ──
        bonus = cfg.bonus if d.month == cfg.bonus_month else 0.0
        freed = mort_monthly if (mort <= 0 and cfg.redirect_freed) else 0.0
        base_cash = savings + bonus + freed - (ee if cfg.payroll_from_savings else 0.0)
        base_cash = max(0.0, base_cash)

        refund_paid = 0.0
        if d.month == cfg.refund_month and refund_due > 0:
            refund_paid, refund_due = refund_due, 0.0
            total_refund += refund_paid
        deploy = 0.0 if cfg.refund_rule == "Spend it" else refund_paid

        if cfg.refund_rule == "All to investments":
            invest_cash, mort_cash = base_cash * p + deploy, base_cash * (1 - p)
        elif cfg.refund_rule == "All to mortgage":
            invest_cash, mort_cash = base_cash * p, base_cash * (1 - p) + deploy
        else:   # "Follow the split" and "Spend it" (deploy is 0 for the latter)
            invest_cash = (base_cash + deploy) * p
            mort_cash   = (base_cash + deploy) - invest_cash

        # ── Mortgage: scheduled payment first, then prepayment ──
        interest = mort * mort_rate_m
        sched_principal = min(mort_monthly - interest, mort) if mort > 0 else 0.0
        # Prepayment can only touch what the scheduled principal leaves behind.
        room_to_prepay = max(0.0, mort - sched_principal)
        cap = (max(0.0, cfg.mort_orig * cfg.prepay_pct / 100 - prepay_used)
               if cfg.prepay_enforce else float("inf"))
        extra = max(0.0, min(mort_cash, room_to_prepay, cap))
        prepay_used += extra
        mort = max(0.0, mort - sched_principal - extra)
        if mort <= 0 and mort_paid_label is None:
            mort_paid_label = lbl

        # Cash the annual prepayment privilege refuses either gets invested or
        # sits idle, depending on the spill setting. Once the mortgage is gone
        # there is nothing to prepay, so it is always invested.
        idle = mort_cash - extra
        if mort <= 0 or cfg.spill_to_invest:
            invest_cash += idle
            idle = 0.0
        total_idle += idle

        # ── Growth, then this month's contributions ──
        for k in bal:
            bal[k] *= 1 + (nonreg_rate_m if k == NONREG else inv_rate_m)

        contrib = {k: 0.0 for k in BUCKETS}
        bal["RRSP – Spouse"] += payroll_in
        contrib["RRSP – Spouse"] += payroll_in
        order = list(cfg.waterfall)
        if NONREG not in order:
            order.append(NONREG)        # always the overflow of last resort
        remaining = invest_cash
        for b in order:
            if remaining <= 1e-9:
                break
            amt = remaining if b == NONREG else min(remaining, max(0.0, room.get(b, 0.0)))
            if amt <= 0:
                continue
            bal[b] += amt
            contrib[b] += amt
            contrib_total[b] += amt
            if b in room:
                room[b] -= amt
            if b.startswith("RRSP"):
                deduct["you" if "You" in b else "sp"] += amt
            remaining -= amt

        rrsp_bal = bal["RRSP – You"] + bal["RRSP – Spouse"]
        gross_total = sum(bal.values())
        net_total = gross_total - rrsp_bal * cfg.rrsp_withdraw_rate / 100
        measure = net_total if cfg.goal_basis == "net" else gross_total

        rows.append({"idx": i, "label": lbl, "mort_bal": mort, "inv_bal": gross_total,
                     "net_bal": net_total, "mort_interest": interest, "mort_extra": extra,
                     "invested": invest_cash, "refund": refund_paid, "idle": idle,
                     "rrsp": rrsp_bal, "tfsa": bal["TFSA – You"] + bal["TFSA – Spouse"],
                     "nonreg": bal[NONREG], **{f"c_{b}": contrib[b] for b in BUCKETS}})

        if goal_label is None and measure >= cfg.goal and (mort <= 0 or not cfg.require_mort_paid):
            goal_label, goal_idx = lbl, i
            break       # stop at the goal; scenarios that miss it run the full horizon

    return {
        "rows": rows, "months_run": len(rows),
        "mort_paid": mort_paid_label or "Not paid off",
        "goal_reached": goal_label,
        "goal_idx": goal_idx if goal_idx is not None else 10 ** 9,
        "final_inv": rows[-1]["inv_bal"], "final_net": rows[-1]["net_bal"],
        "final_mort": rows[-1]["mort_bal"], "final_rrsp": rows[-1]["rrsp"],
        "final_tfsa": rows[-1]["tfsa"], "final_nonreg": rows[-1]["nonreg"],
        "total_interest": sum(r["mort_interest"] for r in rows),
        "total_invested": sum(r["invested"] for r in rows),
        "total_prepaid": sum(r["mort_extra"] for r in rows),
        "total_refund": total_refund, "total_idle": total_idle,
        "total_payroll": total_payroll, "contrib_total": contrib_total,
        "room_left": dict(room),
    }


def generate_colors(n):
    colors = []
    for i in range(max(n, 1)):
        r, g, b = colorsys.hls_to_rgb((i / max(n, 1) + 0.56) % 1.0, 0.62, 0.85)
        colors.append(f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}")
    return colors


def money(x):
    return f"${x:,.0f}"


# ─── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ⚙️ Settings")

    with st.expander("👤 Household income", expanded=True):
        inc_you = st.number_input("Your gross salary ($/yr)", value=130_000.0, min_value=0.0,
                                  step=1_000.0, format="%.0f", key="inc_you")
        inc_sp = st.number_input("Spouse gross salary ($/yr)", value=67_000.0, min_value=0.0,
                                 step=1_000.0, format="%.0f", key="inc_sp")
        salary_growth = st.number_input("Annual salary growth (%)", value=0.0, min_value=0.0,
                                        max_value=15.0, step=0.5, key="salary_growth")

    with st.expander("💵 Cash flow", expanded=True):
        savings = st.number_input("Monthly savings ($)", value=5_000.0, min_value=0.0,
                                  step=100.0, format="%.0f", key="savings")
        expenses = st.number_input("Monthly expenses ($)", value=7_000.0, min_value=0.0,
                                   step=100.0, format="%.0f", key="expenses")
        st.caption(f"Expenses are for reference only — they size the FIRE target below, "
                   f"they are not deducted from savings. 25× annual expenses = "
                   f"{money(expenses * 12 * 25)}.")
        savings_growth = st.number_input("Annual savings growth (%)", value=0.0, min_value=0.0,
                                         max_value=20.0, step=0.5, key="savings_growth")
        bonus = st.number_input("Extra annual bonus ($)", value=0.0, min_value=0.0,
                                step=500.0, format="%.0f", key="bonus")
        bonus_month = st.selectbox("Bonus month", range(1, 13), index=3,
                                   format_func=lambda m: MONTHS_ABBR[m - 1], key="bonus_month")
        st.caption("Separate from the tax refund, which is computed below.")

    with st.expander("🏦 Current balances"):
        rrsp_bal_you = st.number_input("RRSP – you ($)", value=64_000.0, min_value=0.0,
                                       step=1_000.0, format="%.0f", key="rrsp_bal_you")
        tfsa_bal_you = st.number_input("TFSA – you ($)", value=16_000.0, min_value=0.0,
                                       step=1_000.0, format="%.0f", key="tfsa_bal_you")
        rrsp_bal_sp = st.number_input("RRSP – spouse ($)", value=0.0, min_value=0.0,
                                      step=1_000.0, format="%.0f", key="rrsp_bal_sp")
        tfsa_bal_sp = st.number_input("TFSA – spouse ($)", value=0.0, min_value=0.0,
                                      step=1_000.0, format="%.0f", key="tfsa_bal_sp")
        nonreg_bal = st.number_input("Non-registered ($)", value=0.0, min_value=0.0,
                                     step=1_000.0, format="%.0f", key="nonreg_bal")
        _tot = rrsp_bal_you + tfsa_bal_you + rrsp_bal_sp + tfsa_bal_sp + nonreg_bal
        st.caption(f"Total invested today: **{money(_tot)}**")

    with st.expander("📥 Contribution room"):
        rrsp_room_you = st.number_input("RRSP room – you ($)", value=50_000.0, min_value=0.0,
                                        step=1_000.0, format="%.0f", key="rrsp_room_you")
        rrsp_room_sp = st.number_input("RRSP room – spouse ($)", value=20_000.0, min_value=0.0,
                                       step=1_000.0, format="%.0f", key="rrsp_room_sp")
        tfsa_room_you = st.number_input("TFSA room – you ($)", value=63_000.0, min_value=0.0,
                                        step=1_000.0, format="%.0f", key="tfsa_room_you")
        tfsa_room_sp = st.number_input("TFSA room – spouse ($)", value=0.0, min_value=0.0,
                                       step=1_000.0, format="%.0f", key="tfsa_room_sp")
        st.caption("Enter each person's own remaining room from their latest CRA notice — "
                   "TFSA and RRSP room is per person, not per household.")
        tfsa_annual = st.number_input("New TFSA room each year ($)", value=7_000.0, min_value=0.0,
                                      step=500.0, format="%.0f", key="tfsa_annual")
        rrsp_accrual_pct = st.number_input("RRSP accrual (% of prior-year income)", value=18.0,
                                           min_value=0.0, max_value=30.0, step=0.5,
                                           key="rrsp_accrual_pct")
        rrsp_annual_max = st.number_input("RRSP annual dollar limit ($)", value=32_490.0,
                                          min_value=0.0, step=500.0, format="%.0f",
                                          key="rrsp_annual_max")
        limit_indexation = st.number_input("Annual indexation of those limits (%)", value=0.0,
                                           min_value=0.0, max_value=10.0, step=0.5,
                                           key="limit_indexation")
        ytd_you = st.number_input("RRSP already contributed this year – you ($)", value=0.0,
                                  min_value=0.0, step=500.0, format="%.0f", key="ytd_you")
        ytd_sp = st.number_input("RRSP already contributed this year – spouse ($)", value=0.0,
                                 min_value=0.0, step=500.0, format="%.0f", key="ytd_sp")
        st.caption("Contributions made earlier this calendar year still earn a refund at the "
                   "next filing, so enter them here. Assumed already netted out of the "
                   "remaining room above.")

    with st.expander("🤝 Spouse group plan"):
        employee_pct = st.number_input("Spouse contributes (% of salary)", value=7.0,
                                       min_value=0.0, max_value=30.0, step=0.5, key="employee_pct")
        employer_pct = st.number_input("Employer matches (% of salary)", value=7.0,
                                       min_value=0.0, max_value=30.0, step=0.5, key="employer_pct")
        plan_kind = st.radio("Plan type", ["Group RRSP", "DC pension"], index=0, key="plan_kind",
                             help="Group RRSP: the employer match is taxable income, both halves "
                                  "are deductible, and both consume the spouse's RRSP room. "
                                  "DC pension: employer money is not income, only the employee "
                                  "half is deductible, and a pension adjustment reduces next "
                                  "year's RRSP room instead.")
        payroll_from_savings = st.checkbox("Fund the spouse's share out of monthly savings",
                                           value=False, key="payroll_from_savings",
                                           help="Off = it comes off her paycheque, so the monthly "
                                                "savings figure above is already net of it.")
        st.caption(f"Group plan flow: {money(inc_sp * (employee_pct + employer_pct) / 100)}/yr "
                   f"({money(inc_sp * employee_pct / 100)} hers + "
                   f"{money(inc_sp * employer_pct / 100)} matched).")

    with st.expander("📈 Returns"):
        inv_return = st.number_input("Annual return (%)", value=7.0, min_value=0.0,
                                     max_value=20.0, step=0.5, key="inv_return")
        nonreg_drag = st.number_input("Tax drag on non-registered returns (%)", value=20.0,
                                      min_value=0.0, max_value=60.0, step=1.0, key="nonreg_drag")
        st.caption("Drag is applied as a haircut to the return earned inside the "
                   "non-registered account only.")

    with st.expander("🏠 Mortgage"):
        mort_bal = st.number_input("Balance ($)", value=270_000.0, min_value=0.0,
                                   step=5_000.0, format="%.0f", key="mort_bal")
        mort_rate = st.number_input("Interest rate (%)", value=5.4, min_value=0.0,
                                    max_value=20.0, step=0.1, key="mort_rate") / 100
        mort_weekly = st.number_input("Scheduled payment ($/week)", value=441.0, min_value=0.0,
                                      step=10.0, format="%.0f", key="mort_weekly")
        prepay_enforce = st.checkbox("Enforce annual prepayment privilege", value=True,
                                     key="prepay_enforce")
        prepay_pct = st.number_input("Privilege (% of original principal per year)", value=15.0,
                                     min_value=0.0, max_value=100.0, step=1.0, key="prepay_pct",
                                     disabled=not prepay_enforce)
        mort_orig = st.number_input("Original principal ($)", value=270_000.0, min_value=0.0,
                                    step=5_000.0, format="%.0f", key="mort_orig",
                                    disabled=not prepay_enforce,
                                    help="The privilege is a percentage of the original amount "
                                         "borrowed, not of the balance outstanding today.")
        spill_to_invest = st.checkbox("Invest cash the privilege blocks", value=True,
                                      key="spill_to_invest",
                                      help="Off = that cash is held back out of the plan "
                                           "entirely rather than invested. It is reported "
                                           "separately, not carried into a later month.")
        redirect_freed = st.checkbox("Redirect the payment once the mortgage is gone", value=True,
                                     key="redirect_freed")
        st.caption(f"Scheduled payment is {money(mort_weekly * 52 / 12)}/mo and is assumed to be "
                   f"paid *outside* the monthly savings figure. Privilege resets each January.")

    with st.expander("🪜 Allocation waterfall"):
        waterfall = st.multiselect("Priority order for invested dollars", BUCKETS,
                                   default=["RRSP – You", "TFSA – You", "TFSA – Spouse",
                                            "RRSP – Spouse"], key="waterfall")
        st.caption("Each bucket fills to its remaining room before the next one starts. "
                   "Non-registered always catches whatever is left over, so it does not need "
                   "to be listed unless you want it earlier in the queue.")

    with st.expander("🧾 Tax refund"):
        refund_month = st.selectbox("Refund lands in", range(1, 13), index=3,
                                    format_func=lambda m: MONTHS_ABBR[m - 1], key="refund_month")
        refund_rule = st.radio("What happens to it",
                               ["Follow the split", "All to investments", "All to mortgage",
                                "Spend it"], index=0, key="refund_rule")
        st.caption("The refund is computed each January from that year's RRSP deductions at "
                   "the household's actual Alberta + federal rates, then paid out in the month "
                   "chosen here.")

    with st.expander("🎯 Goal & horizon", expanded=True):
        goal = st.number_input("Target portfolio ($)", value=600_000.0, min_value=10_000.0,
                               step=10_000.0, format="%.0f", key="goal")
        goal_basis = st.radio("Measured on", ["Gross balances", "After-tax (RRSP discounted)"],
                              index=0, key="goal_basis")
        rrsp_withdraw_rate = st.number_input("Assumed RRSP withdrawal tax rate (%)", value=25.0,
                                             min_value=0.0, max_value=60.0, step=1.0,
                                             key="rrsp_withdraw_rate")
        require_mort_paid = st.checkbox("Goal also requires the mortgage cleared", value=True,
                                        key="require_mort_paid")
        horizon_years = st.number_input("Horizon (years)", value=10, min_value=1, max_value=40,
                                        step=1, key="horizon_years")
        st.markdown("**Splits to sweep**")
        c1, c2, c3 = st.columns(3)
        sweep_lo = c1.number_input("From %", value=1, min_value=0, max_value=100, step=1, key="lo")
        sweep_hi = c2.number_input("To %", value=99, min_value=0, max_value=100, step=1, key="hi")
        sweep_step = c3.number_input("Step", value=1, min_value=1, max_value=50, step=1, key="step")


# ─── Header ───────────────────────────────────────────────────────────────────
st.markdown("# 🎯 Coast FIRE Scenario Planner")
st.markdown(f"*{horizon_years}-year projection — find the optimal invest/prepay split to reach "
            f"{money(goal)} invested{' + a paid-off home' if require_mort_paid else ''} · "
            f"savings: {money(savings)}/mo · RRSP + TFSA room and the Alberta tax refund modelled*")

# ─── Tax tables ───────────────────────────────────────────────────────────────
# Rendered before the simulation so an edit here feeds straight into the run.
def bracket_df(brackets):
    return pd.DataFrame([{"Up to ($)": None if lim == float("inf") else lim,
                          "Rate (%)": rate * 100} for lim, rate in brackets])


def parse_brackets(df, fallback):
    """Turn the edited table back into (limit, rate) pairs, lowest bracket first.

    Rows are sorted by limit and the top one always runs to infinity, so a partly
    filled or out-of-order table still produces a usable schedule.
    """
    rows = []
    for _, r in df.iterrows():
        rate = r.get("Rate (%)")
        if rate is None or pd.isna(rate):
            continue
        lim = r.get("Up to ($)")
        rows.append((float("inf") if lim is None or pd.isna(lim) else float(lim), float(rate) / 100))
    if not rows:
        return fallback
    rows.sort(key=lambda t: t[0])
    rows[-1] = (float("inf"), rows[-1][1])
    return rows


with st.expander("🧾 Tax engine — federal & Alberta brackets (editable)"):
    st.caption("Defaults are the 2025 federal and Alberta schedules. Leave the top row's "
               "limit blank — the highest bracket always runs to infinity. Add or delete rows "
               "to roll the tables forward.")
    tc1, tc2, tc3 = st.columns([2, 2, 1.4])
    with tc1:
        st.markdown("**Federal**")
        fed_df = st.data_editor(bracket_df(FED_BRACKETS_DEFAULT), num_rows="dynamic",
                                hide_index=True, width="stretch", key="fed_df")
    with tc2:
        st.markdown("**Alberta**")
        ab_df = st.data_editor(bracket_df(AB_BRACKETS_DEFAULT), num_rows="dynamic",
                               hide_index=True, width="stretch", key="ab_df")
    with tc3:
        st.markdown("**Personal amounts**")
        fed_bpa = st.number_input("Federal BPA ($)", value=FED_BPA_DEFAULT, min_value=0.0,
                                  step=100.0, format="%.0f", key="fed_bpa")
        ab_bpa = st.number_input("Alberta BPA ($)", value=AB_BPA_DEFAULT, min_value=0.0,
                                 step=100.0, format="%.0f", key="ab_bpa")
        st.caption("Credited at the lowest bracket rate.")
    fed_brackets = parse_brackets(fed_df, FED_BRACKETS_DEFAULT)
    ab_brackets = parse_brackets(ab_df, AB_BRACKETS_DEFAULT)
    st.caption("CPP and EI are excluded. They are identical with and without an RRSP "
               "deduction, so they cancel out of the refund — but the tax figures below are "
               "income tax only, not full payroll withholding.")

# ─── Build the configuration ──────────────────────────────────────────────────
START_MONTH = next_month_start()
cfg = Cfg(
    you=Person("You", inc_you, rrsp_bal_you, tfsa_bal_you, rrsp_room_you, tfsa_room_you, ytd_you),
    spouse=Person("Spouse", inc_sp, rrsp_bal_sp, tfsa_bal_sp, rrsp_room_sp, tfsa_room_sp,
                  ytd_sp, employee_pct, employer_pct),
    savings=savings, savings_growth=savings_growth, salary_growth=salary_growth,
    bonus=bonus, bonus_month=bonus_month,
    nonreg_bal=nonreg_bal, inv_return=inv_return, nonreg_drag=nonreg_drag,
    tfsa_annual=tfsa_annual, rrsp_accrual_pct=rrsp_accrual_pct,
    rrsp_annual_max=rrsp_annual_max, limit_indexation=limit_indexation,
    group_is_rrsp=(plan_kind == "Group RRSP"), payroll_from_savings=payroll_from_savings,
    mort_bal=mort_bal, mort_rate=mort_rate, mort_weekly=mort_weekly, mort_orig=mort_orig,
    prepay_pct=prepay_pct, prepay_enforce=prepay_enforce, redirect_freed=redirect_freed,
    waterfall=waterfall, spill_to_invest=spill_to_invest,
    refund_month=refund_month, refund_rule=refund_rule,
    fed_brackets=fed_brackets, ab_brackets=ab_brackets, fed_bpa=fed_bpa, ab_bpa=ab_bpa,
    goal=goal, goal_basis="net" if goal_basis.startswith("After-tax") else "gross",
    rrsp_withdraw_rate=rrsp_withdraw_rate, require_mort_paid=require_mort_paid,
    max_months=int(horizon_years) * 12, start=START_MONTH,
)

if cfg.mort_bal > 0 and cfg.mort_weekly * 52 / 12 <= cfg.mort_bal * cfg.mort_rate / 12:
    st.warning(f"The scheduled payment of {money(cfg.mort_weekly * 52 / 12)}/mo does not cover "
               f"the first month's interest of {money(cfg.mort_bal * cfg.mort_rate / 12)}. "
               f"The balance will grow unless prepayments cover the gap.")

# ─── Today's tax position ─────────────────────────────────────────────────────
sp_gross_now = cfg.spouse.income + (cfg.spouse.income * employer_pct / 100 if cfg.group_is_rrsp else 0.0)
st.markdown("### 🧾 Tax position")
t1, t2, t3, t4 = st.columns(4)
t1.metric("Your marginal rate", f"{marginal_rate(cfg.you.income, cfg):.1%}",
          f"tax {money(total_tax(cfg.you.income, cfg))}")
t2.metric("Spouse marginal rate", f"{marginal_rate(sp_gross_now, cfg):.1%}",
          f"tax {money(total_tax(sp_gross_now, cfg))}")
t3.metric("Refund per $10k you contribute", money(refund_for(cfg.you.income, 10_000, cfg)),
          "RRSP – You")
t4.metric("Refund per $10k spouse contributes", money(refund_for(sp_gross_now, 10_000, cfg)),
          "RRSP – Spouse")
st.caption("Marginal rate is the combined federal + Alberta rate on the next dollar earned. "
           "Refunds are valued as a full recalculation of tax with and without the deduction, "
           "so a contribution straddling a bracket is priced correctly.")

# ─── Run the sweep ────────────────────────────────────────────────────────────
pcts = sorted({min(100, max(0, p)) for p in range(int(sweep_lo), int(sweep_hi) + 1, int(sweep_step))})
if not pcts:
    pcts = [50]
colors = generate_colors(len(pcts))
sim_results = []
for pct, color in zip(pcts, colors):
    res = run_scenario(cfg, pct)
    res.update({"name": f"{pct}% Invest / {100 - pct}% Mortgage", "color": color,
                "invest_pct": pct})
    sim_results.append(res)
N = len(sim_results)

# Mirror how run_scenario resolves the waterfall, so the caption cannot claim an
# order the simulation does not actually use.
display_order = list(waterfall)
if NONREG not in display_order:
    display_order.append(NONREG)
st.markdown(f'<div class="info-box">Every split from <b>{pcts[0]}%</b> to <b>{pcts[-1]}%</b> '
            f'invested (step {int(sweep_step)}) is projected on <b>{money(savings)}/mo</b> '
            f'savings. Invested dollars fill <b>{" → ".join(display_order)}</b> in that order, '
            f'to the room available. Adjust anything in the sidebar — results update '
            f'instantly.</div>', unsafe_allow_html=True)

goal_reached = [r for r in sim_results if r["goal_reached"]]
winner = min(goal_reached, key=lambda r: r["goal_idx"]) if goal_reached else None
# Across the sweep the fastest date is usually a plateau rather than a single
# winner, so track everyone who ties instead of crowning the lowest percentage.
tied = [r for r in goal_reached if r["goal_idx"] == winner["goal_idx"]] if winner else []

# ─── Winner banner ────────────────────────────────────────────────────────────
st.divider()
st.markdown("### Results")

if winner:
    band = (f"{tied[0]['invest_pct']}%–{tied[-1]['invest_pct']}% invest"
            if len(tied) > 1 else winner["name"])
    note = (f"📈 {len(tied)} splits tie — anything in that band is equally fast"
            if len(tied) > 1 else f"📈 {winner['invest_pct']}% invest")
    st.markdown(f"""
    <div style="background:linear-gradient(90deg,#1a3a2a,#122a1e);border-left:4px solid #51cf66;
    border-radius:8px;padding:12px 20px;margin-bottom:16px;font-family:'Space Mono',monospace;">
    🏆 <b style="color:#51cf66">FASTEST PATH:</b> &nbsp;
    <span style="color:#e8eaf0">{band}</span> &nbsp;—&nbsp;
    <span style="color:#51cf66">Goal reached {winner['goal_reached']}</span> &nbsp;|&nbsp;
    {note} &nbsp;|&nbsp; 💰 {money(savings)}/mo &nbsp;|&nbsp;
    🧾 {money(winner['total_refund'])} of refunds along the way
    </div>
    """, unsafe_allow_html=True)
    w1, w2, w3, w4, w5 = st.columns(5)
    w1.metric("🏠 Mortgage cleared", winner["mort_paid"])
    w2.metric("🧓 RRSP", money(winner["final_rrsp"]))
    w3.metric("🛡 TFSA", money(winner["final_tfsa"]))
    w4.metric("📇 Non-registered", money(winner["final_nonreg"]))
    w5.metric("💸 Mortgage interest", money(winner["total_interest"]))
else:
    st.markdown(f"""
    <div style="background:linear-gradient(90deg,#3a1a1a,#2a1212);border-left:4px solid #ff6b6b;
    border-radius:8px;padding:12px 20px;margin-bottom:16px;font-family:'Space Mono',monospace;color:#ff6b6b;">
    ⚠️ No split reaches {money(goal)}{' + a paid-off home' if require_mort_paid else ''} within
    {horizon_years} years. Try a longer horizon, more savings, or a higher return.
    </div>
    """, unsafe_allow_html=True)

# ─── Results table ────────────────────────────────────────────────────────────
comp_rows = []
for r in sim_results:
    is_w = bool(winner and r["goal_reached"] and r["goal_idx"] == winner["goal_idx"])
    comp_rows.append({
        "🏷 Scenario":     r["name"],
        "📈 Invest %":     f"{r['invest_pct']}%",
        "🏠 Mortgage %":   f"{100 - r['invest_pct']}%",
        "🎯 Goal Reached": r["goal_reached"] or "—",
        "⏱ Months Run":   f"{r['months_run']}" + ("" if r["goal_reached"] else " (max)"),
        "🏠 Mort Paid":    r["mort_paid"],
        "🧓 RRSP":         money(r["final_rrsp"]),
        "🛡 TFSA":         money(r["final_tfsa"]),
        "📇 Non-reg":      money(r["final_nonreg"]),
        "📊 Total":        money(r["final_inv"]),
        "💧 After-tax":    money(r["final_net"]),
        "🧾 Refunds":      money(r["total_refund"]),
        "💸 Interest":     money(r["total_interest"]),
        "🏆":              "✅" if is_w else "",
    })

st.caption("Each run stops the month its goal is met, so balances and interest are measured at "
           "that point — not over a common horizon. **Months Run** is the window behind each "
           f"row; rows marked *(max)* never met the goal and ran the full {horizon_years} years. "
           f"**After-tax** discounts RRSP balances by {rrsp_withdraw_rate:.0f}%.")
st.dataframe(pd.DataFrame(comp_rows), width="stretch", hide_index=True,
             height=min(42 * N + 60, 620))

# ─── Charts ───────────────────────────────────────────────────────────────────
st.divider()
st.markdown("### Charts")

# A sweep this wide makes a legend useless, so it is off — hover names the split.
CHART_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(13,20,34,0.8)",
    font=dict(color="#7c90b0", family="Syne"),
    showlegend=False,
    margin=dict(t=20, b=20, l=10, r=10),
    # Runs stop at different months, so pin the category order instead of letting
    # it be inferred from whichever trace happens to be drawn first.
    xaxis=dict(gridcolor="#1e2d45", linecolor="#2a3550", categoryorder="array",
               categoryarray=[month_label(cfg, i) for i in range(cfg.max_months)]),
    yaxis=dict(gridcolor="#1e2d45", linecolor="#2a3550", tickprefix="$"),
)
LINE_W = 1.2
st.caption("Colour runs from the lowest invest % to the highest. Hover any line to identify it.")

tabs = st.tabs(["📈 Portfolio Growth", "🏠 Mortgage Balance", "💧 After-tax Portfolio",
                "📊 Monthly Invested", "🧩 Account Mix"])

def sweep_chart(tab, key, goal_line=False):
    with tab:
        fig = go.Figure()
        if goal_line:
            fig.add_hline(y=goal, line_dash="dash", line_color="#ffd43b", line_width=1.5,
                          annotation_text=f"{money(goal)} Goal", annotation_font_color="#ffd43b",
                          annotation_position="top left")
        for r in sim_results:
            fig.add_trace(go.Scatter(
                x=[row["label"] for row in r["rows"]], y=[row[key] for row in r["rows"]],
                name=r["name"], line=dict(color=r["color"], width=LINE_W),
                hovertemplate="%{x}<br>$%{y:,.0f}<extra>" + r["name"] + "</extra>"))
        fig.update_layout(height=500, **CHART_LAYOUT)
        st.plotly_chart(fig, width="stretch")

sweep_chart(tabs[0], "inv_bal", goal_line=(cfg.goal_basis == "gross"))
sweep_chart(tabs[1], "mort_bal")
sweep_chart(tabs[2], "net_bal", goal_line=(cfg.goal_basis == "net"))
sweep_chart(tabs[3], "invested")

with tabs[4]:
    mix_src = winner or sim_results[0]
    st.caption(f"Where the money sits over time under **{mix_src['name']}**"
               + (" (the fastest split)." if winner else "."))
    figm = go.Figure()
    for key, label, col in [("rrsp", "RRSP", "#4dabf7"), ("tfsa", "TFSA", "#51cf66"),
                            ("nonreg", "Non-registered", "#ffd43b")]:
        figm.add_trace(go.Scatter(
            x=[row["label"] for row in mix_src["rows"]], y=[row[key] for row in mix_src["rows"]],
            name=label, mode="lines", stackgroup="one", line=dict(width=0.5, color=col),
            hovertemplate="%{x}<br>$%{y:,.0f}<extra>" + label + "</extra>"))
    figm.update_layout(height=500, **{**CHART_LAYOUT, "showlegend": True,
                                      "legend": dict(orientation="h", y=1.08)})
    st.plotly_chart(figm, width="stretch")

# ─── Month-by-month detail ────────────────────────────────────────────────────
st.divider()
st.markdown("### 📅 Month-by-Month Detail")

default_idx = next((i for i, r in enumerate(sim_results)
                    if winner and r["invest_pct"] == winner["invest_pct"]), 0)
sel = st.selectbox("Scenario", range(N), index=default_idx,
                   format_func=lambda i: sim_results[i]["name"], key="detail_scenario")
detail = sim_results[sel]
# index= only applies on first render, so the dropdown keeps whatever was picked
# even after the winner moves. Call the fastest band out separately.
if winner and detail["goal_idx"] != winner["goal_idx"]:
    band = (f"{tied[0]['invest_pct']}%–{tied[-1]['invest_pct']}% invest ({len(tied)} splits tie)"
            if len(tied) > 1 else f"**{winner['name']}**")
    st.caption(f"🏆 Fastest at these settings is {band} — goal {winner['goal_reached']}. "
               f"Showing {detail['name']}.")

d1, d2, d3, d4 = st.columns(4)
d1.metric("🧾 Refunds received", money(detail["total_refund"]))
d2.metric("🏠 Extra to mortgage", money(detail["total_prepaid"]))
d3.metric("🤝 Group plan in", money(detail["total_payroll"]))
d4.metric("💤 Cash left idle", money(detail["total_idle"]),
          help="Cash the annual prepayment privilege refused while spilling was off. It is "
               "held back out of the plan rather than carried into a later month.")

left = detail["room_left"]
st.markdown(f'<div class="info-box">Room left at stop — '
            f'RRSP you {money(left["RRSP – You"])} · RRSP spouse {money(left["RRSP – Spouse"])} · '
            f'TFSA you {money(left["TFSA – You"])} · TFSA spouse {money(left["TFSA – Spouse"])}'
            f'</div>', unsafe_allow_html=True)

# Group the projection into calendar years — the first and last are part years,
# since the run starts next month rather than in January.
years = {}
for row in detail["rows"]:
    years.setdefault(month_date(cfg, row["idx"]).year, []).append(row)

goal_row = detail["goal_idx"] if detail["goal_reached"] else None
for ytab, (yr, yrows) in zip(st.tabs([str(y) for y in years]), years.items()):
    with ytab:
        first, last = yrows[0], yrows[-1]
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("🏠 Mortgage at year end", money(last["mort_bal"]),
                  f"{last['mort_bal'] - first['mort_bal']:+,.0f}")
        c2.metric("📊 Portfolio at year end", money(last["inv_bal"]),
                  f"{last['inv_bal'] - first['inv_bal']:+,.0f}")
        c3.metric("💵 Invested this year", money(sum(r["invested"] for r in yrows)),
                  f"{len(yrows)} mo")
        c4.metric("🧾 Refund this year", money(sum(r["refund"] for r in yrows)))
        st.dataframe(pd.DataFrame([{
            "Month":       r["label"] + ("  🎯" if r["idx"] == goal_row else ""),
            "🏠 Mortgage": money(r["mort_bal"]),
            "🧓 RRSP":     money(r["rrsp"]),
            "🛡 TFSA":     money(r["tfsa"]),
            "📇 Non-reg":  money(r["nonreg"]),
            "💵 Invested": money(r["invested"]),
            "🏠 Extra":    money(r["mort_extra"]),
            "🧾 Refund":   money(r["refund"]),
            "💸 Interest": money(r["mort_interest"]),
        } for r in yrows]), width="stretch", hide_index=True,
            height=42 * len(yrows) + 45)
        if goal_row is not None and any(r["idx"] == goal_row for r in yrows):
            st.caption(f"🎯 Goal reached {detail['goal_reached']} — {money(goal)} "
                       + ("after tax" if cfg.goal_basis == "net" else "invested")
                       + (" with the mortgage cleared." if require_mort_paid else "."))

st.markdown(f"""
<div class="info-box" style="margin-top:16px;text-align:center">
⚠️ Each scenario runs from {month_label(cfg, 0)} until it reaches the goal, capped at
{horizon_years} years ({cfg.max_months} months, {month_label(cfg, cfg.max_months - 1)}) ·
{money(mort_weekly)}/wk mortgage at {mort_rate:.2%} · the freed-up payment is redirected after payoff ·
RRSP and TFSA room is enforced and tops up every January · the refund is computed from each
year's RRSP deductions at Alberta + federal rates and paid the following {MONTHS_ABBR[refund_month - 1]}.<br>
Monthly savings are assumed to be <b>surplus on top of</b> the scheduled mortgage payment, and
opening balances are taken as at today rather than re-dated as the start month rolls forward.<br>
Income tax only — CPP and EI are excluded, and provincial/federal credits beyond the basic
personal amount are not modelled. For planning purposes only, not tax advice.
</div>
""", unsafe_allow_html=True)
